# Generated by Django 6.0.5 on 2026-05-09 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-is_urgent', '-created_at'], 'verbose_name': 'Annonce', 'verbose_name_plural': 'Annonces'},
        ),
        migrations.AlterModelOptions(
            name='listingimage',
            options={'ordering': ['sort_order'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=20, verbose_name='Icône'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='listings.category', verbose_name='Catégorie parente'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, default='Paris', max_length=50, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=25, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='contact_wechat',
            field=models.CharField(blank=True, max_length=50, verbose_name='WeChat'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='expires_at',
            field=models.DateTimeField(verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='Urgent'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix (€)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price_negotiable',
            field=models.BooleanField(default=False, verbose_name='Prix négociable'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Vendue'), ('expired', 'Expirée'), ('draft', 'Brouillon'), ('rejected', 'Rejetée')], default='active', max_length=10, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Vues'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to='listings/%Y/%m/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing', verbose_name='Annonce'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Ordre'),
        ),
    ]
